- gptqmodel/models/base.py
if conversion is needed, we need to use the converted model state_dict().
> [BUG] fix save_quantized() use wrong model to obtain state_dict()

- gptqmodel/models/base.py
- gptqmodel/utils/data.py
Original code had broken batching support. Causing quantization of large calibration to take much longer than necessary.
> [FIX] Batching of calibration data in .quantize()

- gptqmodel/models/deepseek_v2.py
init method is executed after from_quantized(), so it cannot obtain the correct layer_modules. 
move correct lite layer_modules to layer_modules
> [FIX] DeepSeek-V2-Lite load

- gptqmodel/models/opt.py
Resolves https://github.com/ModelCloud/GPTQModel/issues/117
For OPT model, the fc1/fc2 layer modules are horrible/in-compatible with current quant calibration resulting in massive losses for every single layer.  Solution is to disable/skip these 2 modules.
> [FIX] opt fc1/fc2 layer modules should not be quantized

- gptqmodel/models/base.py
- gptqmodel/nn_modules/qlinear/__init__.py
- gptqmodel/nn_modules/qlinear/qlinear_bitblas.py
- gptqmodel/nn_modules/qlinear/qlinear_cuda.py
- gptqmodel/nn_modules/qlinear/qlinear_cuda_old.py
- gptqmodel/nn_modules/qlinear/qlinear_exllama.py
- gptqmodel/nn_modules/qlinear/qlinear_exllamav2.py
- gptqmodel/nn_modules/qlinear/qlinear_marlin.py
- gptqmodel/nn_modules/qlinear/qlinear_tritonv2.py
- gptqmodel/utils/bitblas.py
- gptqmodel/utils/exllama.py
- gptqmodel/utils/importer.py
- gptqmodel/utils/marlin.py
- gptqmodel/utils/model.py
https://github.com/ModelCloud/GPTQModel/issues/110
> [REFRACTOR] remove Quant_Type and rename QuantLinear with type

- gptqmodel/nn_modules/qlinear/bitblas_target_detector.py
- gptqmodel/nn_modules/qlinear/qlinear_bitblas.py
- install.sh
- requirements.txt
This pull request includes a change to the `install.sh` script to export the `TORCH_CUDA_ARCH_LIST`  variables in install.sh scripts. Otherwise, the build pipeline of cuda backend will crash.
Also remove `importlib` from requirements.txt ref to #132
> [Fix] Export TORCH_CUDA_ARCH_LIST in install.sh

- gptqmodel/models/opt.py
This reverts commit c9a0688809238543b221654c2f0f9385d0e521a7.
Even though PPL improved fc1/fc2 omission there were too many inference incompatibility to warrant this change.
> Revert "fix opt fc1/fc2 layer modules should not be quantized (#118)"

- gptqmodel/models/base.py
Need higher precision in avg_loss logs due to some modules showing `0.0000` during quants. Reduce the precison for time logs since humans don't need/care for sub-ms timings.
> increase log precision in avg_loss and decrease for time taken

- gptqmodel/models/base.py
- gptqmodel/utils/model.py
- tests/test_quant_batch.py
Prefix-less (without `layers_node` prefix) regex matching makes life easier for users but becomes a headache for vllm/sgalng. Remove for now.
> revert prefix-less regex matching

- gptqmodel/models/auto.py
- gptqmodel/nn_modules/qlinear/qlinear_exllama.py
Still need this change to run `quantization/basic_usage.py` in a CPU-only device.
> fix cpu/xpu backend selection

- gptqmodel/nn_modules/qlinear/qlinear_ipex.py
This bug was found in peft tests. Fixed with disable ipex linear when input data requires grad.
> fix ipex linear check

- gptqmodel/nn_modules/qlinear/ipex.py
Fix xpu training by changing the init tensor to input data's device. Remove duplicated 4bit check.
> Fix XPU training

- gptqmodel/nn_modules/qlinear/dynamic_cuda.py
- gptqmodel/utils/importer.py
IPEX don't need to install cuda lib, will cache it in the dynamic cuda qlinear.
Also fixed too much logs, I suppose we only need to log once because all qlinears in a model should have the same backend.
> fix ipex cpu backend import error and fix too much logs

- gptqmodel/nn_modules/qlinear/ipex.py
- gptqmodel/quantization/gptq.py
- gptqmodel/utils/importer.py
1. Fix ipex linear: remove support for group_size=-1; remove sym hard setting
2. Fix logging once by a global env param.
3. Use XPU sync and empty cache in fasterquant
> Fixed ipex linear param check and logging once

- tests/models/test_gptbigcode.py
if intel_extension_for_pytorch was installed, @torch.jit.script in transformers/models/gpt_bigcode/modeling_gpt_bigcode.py will try to use ipex as torchScript interpreter.
However, in quantization, tensor were on gpu, which will throw RuntimeError: itensor_view_from_dense expects CPU tensor input
> fix gptbigcode test temporally

- gptqmodel/models/loader.py
- tests/models/model_test.py
- tests/models/test_minicpm.py
- tests/test_perplexity.py
- tests/test_quant_trust_remote.py
if Version(transformers.__version__) >= Version("4.46.0"):
args["_attn_implementation_autoset"] = True
move these codes from loader.py to minicpm tests only
> fix ppl test

- gptqmodel/models/_const.py
- gptqmodel/models/auto.py
- gptqmodel/models/definitions/__init__.py
- gptqmodel/models/definitions/telechat2.py
Add support for the Telechat model (VLLM now supports the Telechat model).
> [MODEL] Add Telechat2 (China Telecom)

- gptqmodel/models/loader.py
- gptqmodel/models/writer.py
- gptqmodel/utils/bitblas.py
- gptqmodel/utils/marlin.py
- gptqmodel/utils/model.py
Call tied_weights() after load_checkpoint_in_model() to have the weights tied correctly.
> [FIX] Call tied_weights() after load_checkpoint_in_model() 

- setup.py
Fix for #1161 
Trying to build the package from source with ROCm for AMD GPUs fails as an environment variable `CUDA_VERSION` is required but not used anywhere.
Here I'm following the simple fix by changing the order of execution in the `get_version_tag` function in setup.py.
More information can be found in the Issue #1161
> fix(build): fix building from source with ROCm

- gptqmodel/models/base.py
- gptqmodel/models/loader.py
- gptqmodel/nn_modules/qlinear/__init__.py
- gptqmodel/nn_modules/qlinear/bitblas.py
- gptqmodel/nn_modules/qlinear/exllama.py
- gptqmodel/nn_modules/qlinear/exllamav2.py
- gptqmodel/nn_modules/qlinear/ipex.py
- gptqmodel/nn_modules/qlinear/marlin.py
- gptqmodel/nn_modules/qlinear/torch.py
- gptqmodel/nn_modules/qlinear/tritonv2.py
- gptqmodel/nn_modules/triton_utils/dequant.py
- gptqmodel/quantization/config.py
- gptqmodel/utils/importer.py
- gptqmodel/utils/marlin.py
- gptqmodel/utils/model.py
- gptqmodel_ext/marlin/marlin_repack.cu
- gptqmodel_ext/marlin/marlin_repack.cuh
Allow quantized weights to be packed in:
* int32 (default, original gptq)
* int16
* int8
Some kernels/gpus may benefit to the different alignments for concurrent dequant
Completed Kernels:
> Flexible Pack DType

- gptqmodel_ext/exllama/cuda_func/q4_matmul.cu
- gptqmodel_ext/exllamav2/cuda/q_gemm_kernel_gptq.cuh
- gptqmodel_ext/exllamav2/cuda/q_matrix.cu
How can decoded qweight and qzeros overlfow? This should not be possible unless quant code failed, packing failed, or de-quant failed.
> Remove overflow saftey code

- gptqmodel/models/auto.py
- gptqmodel/models/base.py
- gptqmodel/quantization/gptq.py
- tests/test_perplexity.py
experimental: `model.quantize(.., buffered_fwd=True)` which may save vram for large models at the expense of longer quant time.
Tests show signficant peak vram reduction but also much longer of quant time. Good choice to enable quantization on low vram gpus for larger models.
> experimental `buffered_fwd` quantize control

- gptqmodel/quantization/config.py
TypeHint Optional/Union should accept `type` vars and not actual type values. Breaks Python 3.10 but not Python 3.12.
Fix https://github.com/ModelCloud/GPTQModel/issues/1212
> Python 3.10 type-hint compt bug

- gptqmodel/models/_const.py
* There was a missing ',' after minicpm which was breaking model detection
* I noticed this after trying to use the PR: https://github.com/ModelCloud/GPTQModel/pull/1116
* Test: Build on local and try out minicpmo
> Fix supported models list (syntax error)

- examples/quantization/basic_usage_wikitext2.py
- gptqmodel/models/definitions/minicpm.py
- gptqmodel/nn_modules/qlinear/__init__.py
- gptqmodel/utils/model.py
> [FIX] not pack when group_size=-1

- .github/workflows/code_quality.yml
- format/format.sh
- requirements.txt
- tests/test_transformers.py
> bump tokenicer to v0.0.3

- .github/workflows/unit_tests.yml
> [CI] fix xpu env has no logbar

- gptqmodel/nn_modules/qlinear/exllama.py
- gptqmodel/nn_modules/qlinear/exllamav2.py
- gptqmodel/nn_modules/qlinear/marlin.py
- gptqmodel_ext/marlin/marlin_cuda_kernel.cu
- tests/models/test_qwen_15_moe.py
Fix upstream transformers modeling inference code is passing impossible input shape where `shape[0]==0` to module
Patch Fixes: https://github.com/ModelCloud/GPTQModel/issues/1361
However, I believe this should not happen at all and fix should be upstream in transformers.
> Fix transformers modeling code passing `input.shape[0] == 0` to nn.module

- gptqmodel/nn_modules/qlinear/tritonv2.py
We need to perform more extensive validations before allowing triton to execute on intel xpu
> tremove xpu support of triton kernel

- gptqmodel/looper/module_looper.py
- gptqmodel/quantization/gptq.py
issue [1376 ](https://github.com/ModelCloud/GPTQModel/issues/1376).  Add a counter and print in the quant logs how many actual add_batch or inputs are captured by the quantization process for each module.
> add fwd counter

- gptqmodel/nn_modules/qlinear/ipex.py
1. We need call super post init to get `wf_unsqueeze_zero`, otherwise we cannot dequant.
2. IPEXWoqLinear is incompatible with torch.compile, we should disable it until we fix this issue.
> fix ipex linear post init for finetune

- gptqmodel/nn_modules/qlinear/__init__.py
- gptqmodel/nn_modules/qlinear/exllama.py
- gptqmodel/nn_modules/qlinear/exllama_eora.py
- gptqmodel/nn_modules/qlinear/exllamav2.py
- gptqmodel/nn_modules/qlinear/marlin.py
- tests/test_q4_marlin.py
fix https://github.com/ModelCloud/GPTQModel/discussions/1379
> Fix bfloat16 kernels

- gptqmodel/models/loader.py
Hi, I noticed an issue while using the gptqmodel. Even though I’ve set the environment variables properly, the model isn’t being downloaded from ModelScope. It seems like the code might be preventing the modelscope snapshot_download logic from executing entirely.
> fix the error when downloading models using modelscope

- gptqmodel/quantization/gptq.py
At block_size = tensor.columns // 2 == 1024
```
Performance Summary (50 runs on 2048x2048 matrix):
Block Version:
Average Time: 0.0011 ± 0.0005 s
Peak Memory: 72.12 ± 0.00 MB
Standard Version:
Average Time: 0.0026 ± 0.0007 s
Peak Memory: 88.13 ± 0.00 MB
Numerical Error Analysis (max absolute difference):
Mean error: 3.3730e-02
Max error: 3.8948e-02
Min error: 3.1047e-02
```
At block_size = tensor.columns // 1. == 2048
```
Performance Summary (50 runs on 2048x2048 matrix):
Block Version:
Average Time: 0.0017 ± 0.0004 s
Peak Memory: 88.12 ± 0.00 MB
Standard Version:
Average Time: 0.0025 ± 0.0009 s
Peak Memory: 88.13 ± 0.00 MB
Numerical Error Analysis (max absolute difference):
Mean error: 1.9632e-08
Max error: 2.6077e-08
Min error: 1.6764e-08
```
> >2x faster cholesky inverse and avoid oom when possible

- examples/benchmark/perplexity.py
- examples/eora/eora_generation.py
- examples/eora/eora_load_and_inference.py
- examples/eora/evaluation.py
- examples/eora/post_quant_eora_generation.py
- examples/inference/run_with_different_backends.py
- examples/quantization/basic_usage.py
- gptqmodel/looper/eora_processor.py
- gptqmodel/looper/gptq_processor.py
- gptqmodel/looper/module_looper.py
- gptqmodel/looper/qqq_processor.py
- gptqmodel/models/writer.py
- gptqmodel/quantization/gptq.py
- tests/benchmark/benchmark_test.py
- tests/models/model_test.py
- tests/test_quant_formats.py
Prelim framework to allow quantization to operate on 2 gpu. Just set `CUDA_VISIBLE_DEVICES=` to two gpus and gptqmodel will use the second GPU for quantization phase. For now, only 2 GPU is used even if you provide > 2. 
However, due to the structure of the current code, peak vram saving is <15% (based on a simple testing)  and quantization speed takes a hit since we need to move multi-GB worth of tensors to/back from GPU0 <-> GPU1.  However 15% peak vram saving is a substantial if your model is just too large for the calibration dataset size on one gpu.
Make sure the two GPUs have at least PCIE 4.0 x4 lanes each.  
This is just the first phase of multi-gpu quantization .
> Multi GPU Quantization

- gptqmodel/utils/torch.py
Removes some log noise: `mx.metal.clear_cache is deprecated and will be removed in a future version. Use mx.clear_cache instead.`
> Switch to non-deprecated mlx.core.clear_cache()

- gptqmodel/nn_modules/qlinear/exllamav2.py
bypass Issue https://github.com/ModelCloud/GPTQModel/issues/1515 until we can validate and check. 
@wenhuach21 I didn't have time to do a thorough check yet but based on your report, I am going to temporarily disable Exllama v2 for groupsize 16.
> disable selection of ExllamaV2 kernel for group_size=16 for now

- gptqmodel/models/base.py
- gptqmodel/nn_modules/qlinear/torch.py
- gptqmodel/quantization/rotation/rotation.py
- gptqmodel/utils/model.py
When embeddings are tied, fusing the `pre_head_layernorm` into `lm_head` also impacts `embed_tokens`. This happens in a few common models: Qwen2.5-0.5B, Llama3.2 for example. Possible this is the source of the issue mentioned in https://github.com/ModelCloud/GPTQModel/pull/1425#issuecomment-2717194335.
The solution is to untie the weights.
Also made some related changes along the way, happy to revert them or split them into separate PRs:
- Allow rotation for all quant_methods. May not always help, but doesn't need to be QQQ-specific.
- Couple small fixes to improve MPS compatibility. (Not perfect, e.g. still need to comment out `rotate_ov_proj`.)
> Fix rotation for tied embedding models

- gptqmodel/quantization/gptq.py
Thanks for the previous support for convolution layers. In this PR, I’ve added fixes for two specific cases:
- Conv1D and unfold parameter requirement:
The unfold operation expects 2D parameters, so for Conv1D layers, both the input tensor and parameters need to be expanded by one dimension to match the expected shape.
- Grouped convolutions:
Fixed the input tensor shape for convolutions that use the groups parameter to ensure the input is correctly formatted and grouped during computation.
ref:
https://pytorch.org/docs/stable/generated/torch.nn.Unfold.html
https://discuss.pytorch.org/t/conv1d-implementation-using-torch-nn-functional-unfold/109643/3
> Fix input processing for convolution

- gptqmodel/eora/eora.py
- gptqmodel/looper/eora_processor.py
- gptqmodel/looper/gptq_processor.py
- gptqmodel/looper/loop_processor.py
- gptqmodel/looper/module_looper.py
- gptqmodel/looper/named_module.py
- gptqmodel/looper/native_processor.py
- gptqmodel/looper/qqq_processor.py
- gptqmodel/models/auto.py
- gptqmodel/models/base.py
- gptqmodel/models/loader.py
- gptqmodel/nn_modules/hooked_linear.py
- gptqmodel/quantization/gptq.py
- gptqmodel/quantization/gptqv2.py
- gptqmodel/utils/torch.py
- tests/models/model_test.py
- tests/models/test_qwen3_moe.py
- tests/test_quant_and_eora.py
Refractor multi-gpu quantization with python threads. Compare to previous efforts:
* 2-3x less memory usage if you assign multiple GPUS up to 3 for Llama/Qwen style or 5 (tested) for MoE style. 
* Performance hit is much reduced verious pervious method. Small model only saw 1% slowdown. 
* This is not tensor-parallel so it will not make things faster, but actually around 1-5% slower dependng on model, gpu, and gpu to gpu memory latency.
With advent of python 3.13-3.14 and pytorch 2.7 concurrent gil context, it is possible to get Nx GPU improvement to MoE quantiation for next major refractor if we can cleanly decouple the thread/module code with multiple python/torch GIL context without any usage of tensor-parallel which I want to avoid at all-costs for now.
> Process threads

- .github/workflows/unit_tests.yml
> [CI] fix unit test was unable to run

- gptqmodel/utils/eval.py
> fix older python didn't have EnumType

- README.md
- gptqmodel/quantization/config.py
- gptqmodel/quantization/gar.py
- gptqmodel/quantization/gptq.py
This PR adds a new experimental feature called Group Aware Reordering (GAR), which improves GPTQ quantization accuracy by reordering activations based on their importance while avoiding inference-time overhead.
The method follows the design from our CVPR Workshop 2025 paper:
> T. Gafni, A. Karnieli, Y. Hanani, "Dual Precision Quantization for Efficient and Accurate Deep Neural Networks Inference," CVPRW 2025.  
> [Paper link](https://openaccess.thecvf.com/content/CVPR2025W/eLVM/html/Gafni_Dual_Precision_Quantization_for_Efficient_and_Accurate_Deep_Neural_Networks_CVPRW_2025_paper.html)
To enable it, set the `hyb_act` parameter to `True` and disable the default activation reordering by setting `desc_act` to `False` in your `QuantizeConfig`. For example:
```python
quant_config = …
```
> Add Group Aware Reordering (GAR) for Efficient Activation Reordering

- gptqmodel/nn_modules/qlinear/torch_fused.py
- gptqmodel/utils/backend.py
- gptqmodel/utils/importer.py
This PR enables XPU to use pytorch fused op, it can bring at least 50% speed-up. Waiting for pytorch 2.8 release
> Enable pytorch fused op on XPU

- gptqmodel/nn_modules/qlinear/exllama.py
- gptqmodel/nn_modules/qlinear/exllama_eora.py
- gptqmodel/nn_modules/qlinear/exllamav2.py
- gptqmodel/nn_modules/qlinear/marlin.py
- gptqmodel/nn_modules/qlinear/qqq.py
The exception `e` is not just an ImportError instance — it also stores a reference to a traceback object.
The traceback contains the entire call stack at the time of the error.
Keeping the exception as a global value will lead to the object not being released, for example:
```python
import sys
import torch
import gc
from diffusers import (
FluxControlPipeline,
FluxTransformer2DModel,
GGUFQuantizationConfig,
)
torch_device = 0
accelerator_module = None
if torch.cuda.is_available():
accelerator_module = torch.cuda
elif torch.xpu.is_available():
accelerator_module = torch.xpu
def test_lora_loading():
ckpt_path = "https://huggingface.co/city96/FLUX.1-dev-gguf/blob/main/flux1-dev-Q2_K.gguf"
transformer = FluxTransformer2DModel.from_single_file(
ckpt_path, …
```
> fix exception to avoid memory issue

- gptqmodel/looper/module_looper.py
- tests/models/model_test.py
Fix hidden states passed inconsistently as kwarg and sometimes as postional args
> Fix kwarg vs pos arg hidden states

- gptqmodel/models/definitions/base_qwen2_vl.py
Fix Qwen 2.5-VL compat with latest transformers.
> [FIX] use AutoModelForImageTextToText instead of AutoModelForVision2Seq

- .github/workflows/unit_tests.yml
> [CI] update torch for build

- gptqmodel/models/auto.py
- gptqmodel/models/definitions/gpt_oss.py
- gptqmodel/nn_modules/qlinear/tritonv2.py
- gptqmodel/utils/__init__.py
- gptqmodel/utils/model.py
- gptqmodel/utils/python.py
- gptqmodel/utils/torch.py
Cleanup some code for GIL checks and also add checks for torch compile which is now compatible with  free-threading but must be >= 3.13.3t.
> cleanup checks for GIL control, GIL=0, and python >= 3.13.3t

- gptqmodel/quantization/gptq.py
We should not assume dtype is fp32. 
Fix https://github.com/ModelCloud/GPTQModel/issues/1777
Fix https://github.com/intel/auto-round/issues/812
> FIX transformers >= 4.56.1 force changed `torch.default_dtype`

- .github/workflows/release.yml
> [CI] torch-2.6.0+cu128-python-3.9 does not exist

- gptqmodel/eora/eora.py
- gptqmodel/looper/dequantize_processor.py
- gptqmodel/looper/eora_processor.py
- gptqmodel/looper/gptq_processor.py
- gptqmodel/looper/module_looper.py
- tests/test_post_quant_eora.py
@nbasyl  We just did a major refractor of internals to add AWQ. Just a little cleanup in the `EoRA` paths. The biggest change is doing all diff in fp32. It appears if the diff in fp16 is very small, it can actually result in 0.0 if we don't upcast to fp32. 
We have not tested awq and eora execution paths but I believe `eora` may also work with `awq`?
> eora: always diff in fp32 + cleanup

- gptqmodel/quantization/gptq.py
@avtc  Reverting previous threading fix for multi-gpu as I believe the recent threaad codes I pushed on `main` has nullified this issue at the source. Please test. Also, massive cpu memory usage has been eliminated including elimination of packing as pack is now done inline to quant.
> remove prev thread fix, replaced by main changes

- examples/quantization/basic_usage_wikitext2.py
- gptqmodel/looper/awq_processor.py
- gptqmodel/models/definitions/gpt_oss.py
- gptqmodel/models/definitions/llama4.py
- gptqmodel/nn_modules/qlinear/__init__.py
- gptqmodel/nn_modules/qlinear/awq_gemm.py
- gptqmodel/nn_modules/qlinear/awq_gemm_ipex.py
- gptqmodel/quantization/awq/modules/linear/gemm.py
- gptqmodel/quantization/awq/modules/linear/gemm_ipex.py
- gptqmodel/quantization/awq/modules/linear/gemv.py
- gptqmodel/quantization/awq/modules/linear/gemv_fast.py
- gptqmodel/quantization/awq/modules/linear/marlin.py
- gptqmodel/quantization/awq/quantize/scale.py
- gptqmodel/utils/bitblas.py
- gptqmodel/utils/mmlupro.py
- gptqmodel/utils/offload.py
- gptqmodel/utils/openai_server.py
- gptqmodel/utils/perplexity.py
- gptqmodel/utils/structure.py
- tests/models/model_test.py
- tests/test_q4_exllama_v1.py
- tests/test_q4_exllama_v2.py
@avtc  please test this which should fix your latest crash about cannot modif tensors inplace without inference mode ctx.
> fix inference mode not applied to threads

- gptqmodel/utils/offload.py
@avtc  missed a huge dealloc ++
> missing offload dealloc tracking

- README.md
- gptqmodel/looper/module_looper.py
- gptqmodel/models/_const.py
- gptqmodel/models/base.py
- gptqmodel/utils/threadx.py
@avtc Another 75% speed reduction off on top of current main branch for MoE quantization. No joke. This PR will actually make smaller non-moe models slower but gives a huge boost to MoE models. The bigger the model, the more gpus will help.
Forwarding is now data-parallel (model is replicated across all gpus and work is sharded)
But based on some small tests, I expect oom possibility to now actually increase because now the model needs to be replicated/copied to mutliple gpu in multiple threads so gpu:0's memory load actually increases.
> Data Parallel

- gptqmodel/looper/awq_processor.py
- gptqmodel/looper/gptq_processor.py
- gptqmodel/looper/qqq_processor.py
- gptqmodel/models/writer.py
- gptqmodel/utils/model.py
> Directly save meta files to disk on model save

- gptqmodel/utils/torch.py
Fix https://github.com/ModelCloud/GPTQModel/issues/1976
`torch.backends.fp32_precision` is added post pytorch 2.8. 
PR tested under torch 2.8 and torch 2.10-dev
> fix tf32 on/off regression
