gptqmodel/nn_modules/qlinear/qlinear_exllama.py, gptqmodel/nn_modules/qlinear/qlinear_exllamav2.py, gptqmodel/utils/exllama.py, gptqmodel/utils/model.py, setup.py, tests/test_q4_bitblas.py, tests/test_q4_cuda.py, tests/test_q4_exallama.py, tests/test_q4_exallama_v2.py, tests/test_q4_marlin.py, tests/test_q4_triton.py
Exllama kernels compiled/installed has conflict with autogptq.
=> [FIX][CORE] Rename exllama_kernels class name to fix import/export conflicts with autogptq

gptqmodel/nn_modules/qlinear/qlinear_bitblas.py, tests/test_lm_head.py, tests/test_perplexity.py, tests/test_q4_cuda.py, tests/test_q4_exallama.py, tests/test_q4_exallama_v2.py, tests/test_quant_formats.py, tests/test_repacking.py, tests/test_serialization.py, tests/test_sharded.py, tests/test_triton.py
Add E402 to appropriate places so ruff check passes.
=> [CI] ignore these E402 errors so ruff passes

gptqmodel/models/base.py, gptqmodel/utils/model.py
it was use_triton here, so this should be backend == Backend.TRITON
=> [FIX] [CORE] Fix triton check

README.md, install.sh
=> [FEATURE] Add UV PIP usage instructions information

gptqmodel/models/base.py, tests/test_quant_formats.py
https://github.com/ModelCloud/GPTQModel/issues/123
=> [FIX] Fix issues 123

gptqmodel/models/auto.py, gptqmodel/models/base.py
=> [REFRACTOR] remove max_memory arg

gptqmodel/models/base.py, gptqmodel/quantization/config.py
=> [FIX]remove autoround_config.nsample, and change low_gpu_mem_usage default

setup.py
ref: https://github.com/vllm-project/vllm/issues/6689#issuecomment-2245935916
=> FIX vllm llama 3.1 support

tests/test_vllm.py
=> [FIX] add release_vllm_model, and import destroy_model_parallel in release_vllm_model

setup.py, tests/test_serialization.py, tests/test_sglang.py
The current project code no longer caches marlin model files, and this test has been removed.
=> [FIX] remove test_marlin_hf_cache_serialization()

.github/workflows/build_wheels_cuda_linux.yml, .github/workflows/unit_tests.yml
1. if both AMD & Intel are online, release will sepearate tasks (half to half ) to 2xAMD & 2xIntel.
2. allow run release for specific repo & commit
3. allow run test with specific docker image
=> [CI] Update docker list & matrix

gptqmodel/models/__init__.py, gptqmodel/models/_const.py, gptqmodel/models/auto.py, gptqmodel/models/minicpm3.py
I am a staff member of Model Best. We have recently open sourced minicpm3.0. This is a model address that uses gtpq to quantify minicpm3.0. It has achieved good results. We look forward to your merger.
https://huggingface.co/openbmb/MiniCPM3-4B-GPTQ-Int4
=> support for minicpm3

README.md
First of all, kudos for this project.
It's the only project I found that properly supports modern models like llama-3.1 out of the box. Also the speed, and other factors, seem better.
Fixing in this PR a small bug - the previous link led to a missing page.
=> Fix missing link

setup.py, tests/test_sglang.py, tests/test_vllm.py
=> [PKG] update vllm/sglang optional depends

setup.py
Misc update. Also will resolve #381
=> [BUILD] update compile flags

gptqmodel/utils/model.py
=> remove needless function

examples/benchmark/generation_speed.py, examples/benchmark/perplexity.py, examples/evaluation/run_language_modeling_task.py, examples/evaluation/run_sequence_classification_task.py, examples/evaluation/run_text_summarization_task.py, examples/quantization/basic_usage.py, examples/quantization/basic_usage_autoround.py, examples/quantization/basic_usage_wikitext2.py
Minus fix for examples to support CPU
=> enable CPU examples

.github/workflows/unit_tests.yml
=> [CI] do checkout first

examples/benchmark/ipex.py
…r of cores to control the number of threads used by OpenMP
=> Set the "OMP_NUM_THREADS" environment

gptqmodel/nn_modules/qlinear/qlinear_bitblas.py, gptqmodel/nn_modules/qlinear/qlinear_cuda.py, gptqmodel/nn_modules/qlinear/qlinear_exllama.py, gptqmodel/nn_modules/qlinear/qlinear_exllamav2.py, gptqmodel/nn_modules/qlinear/qlinear_ipex.py, gptqmodel/nn_modules/qlinear/qlinear_marlin.py, gptqmodel/nn_modules/qlinear/qlinear_torch.py, gptqmodel/nn_modules/qlinear/qlinear_tritonv2.py
For optimum and transformers check qlinear quant type tests
=> add QUANT_TYPE in qlinear

gptqmodel/utils/importer.py
This could fix the backend to auto when device_map in ["cuda", "auto"]
=> fix select quant linear

gptqmodel/models/base.py, gptqmodel/models/definitions/hymba.py, gptqmodel/models/loader.py
Resolved [issue#712](https://github.com/ModelCloud/GPTQModel/issues/712)
=> BaseModel add supports_desc_act

gptqmodel/quantization/config.py, gptqmodel/utils/model.py, tests/test_dynamic.py
Fix issue: https://github.com/ModelCloud/GPTQModel/issues/905
=> [FIX] the error of loading quantized model with dynamic

gptqmodel/quantization/config.py
Partial fix for issue mentioned in https://github.com/ModelCloud/GPTQModel/issues/977#issuecomment-2564606211
=> [FIX] quantize_config could not read from config.json

.github/workflows/unit_tests.yml
=> [CI] fix assert

gptqmodel/models/base.py, tests/models/model_test.py
=> supress dynamo error

gptqmodel/nn_modules/qlinear/exllama.py, gptqmodel/nn_modules/qlinear/ipex.py, gptqmodel/nn_modules/qlinear/torch.py, gptqmodel/nn_modules/qlinear/tritonv2.py, tests/test_packing.py, tests/test_q4_torch.py
=> optimize pack

README.md, gptqmodel/models/base.py, gptqmodel/models/loader.py, gptqmodel/nn_modules/qlinear/__init__.py, gptqmodel/nn_modules/qlinear/exllama.py, gptqmodel/nn_modules/qlinear/torch.py, gptqmodel/nn_modules/qlinear/tritonv2.py, gptqmodel/utils/importer.py, gptqmodel/utils/model.py, gptqmodel/utils/safetensor.py, tests/models/model_test.py, tests/test_dynamic.py
=> Add `pack_dtype` to dynamic config and fix validate

examples/benchmark/perplexity.py
Fix https://github.com/ModelCloud/GPTQModel/issues/1190
=> Fix examples/perplexity

gptqmodel/models/auto.py, gptqmodel/models/base.py, gptqmodel/quantization/gptq.py, requirements.txt, setup.py, tests/test_packing_speed.py, tests/test_perplexity.py
via static class method api. Log error if user is using model instance.push_to_hub() api.
=> add `GPTQModel.push_to_hub()` support

gptqmodel/models/base.py, gptqmodel/nn_modules/qlinear/__init__.py, gptqmodel/utils/model.py
=> fix 3bit packing and inference

setup.py
=> Fix rocm compile flags regression

setup.py
=> add license to setup.py

gptqmodel/models/base.py, gptqmodel/models/loader.py, gptqmodel/models/writer.py, gptqmodel/utils/model.py, requirements.txt
Offload tokenizer patching and normalization with [Toke(n)icer](https://github.com/modelcloud/tokenicer)
=> Use Toke(n)icer

.github/workflows/unit_tests.yml
=> [CI] install tokenicer for ci

gptqmodel/models/base.py
=> fix trust_remote was lost

gptqmodel/utils/importer.py
=> fix not enough values to unpack (expected 2, got 1)

.github/workflows/unit_tests.yml
=> fix sglang test requires numpy<2.0

gptqmodel/nn_modules/qlinear/ipex.py, gptqmodel/utils/importer.py
=> ipex should be packable, reverted pr #1259 importer.py changes

.github/workflows/unit_tests.yml, gptqmodel/models/base.py, gptqmodel/quantization/gptq.py, tests/models/model_test.py, tests/test_transformers.py
=> add transformers test

tests/models/model_test.py, tests/test_q4_torch.py
=> [CI] fix outputs are not enough

.github/workflows/unit_tests.yml
=> [CI] fix transformers version was overrided

.github/workflows/unit_tests.yml
=> [CI] remove peft & fix torch was upgraded by optimum

.github/workflows/unit_tests.yml, gptqmodel/__init__.py, gptqmodel/models/loader.py, tests/test_modelscope.py
=> fix modelscope import & tests

gptqmodel/models/auto.py
=> fix lm-eval & vllm check tokenizer type

gptqmodel/models/writer.py, requirements.txt
FIX https://github.com/ModelCloud/GPTQModel/issues/1291
Needs testing. Untested
=> Fix `generation_config.json` not auto-saved

tests/test_bits.py
=> print expected value

gptqmodel/quantization/config.py, tests/test_quant_formats.py, tests/test_quant_formats_auto_round.py
=> clean is_marlin_format for tests

gptqmodel/quantization/__init__.py, gptqmodel/quantization/config.py, requirements.txt
=> bump tokenicer to 0.0.4 & remove FORMAT_FIELD_COMPAT_MARLIN

.github/workflows/unit_tests.yml
=> [CI] fix CI url

.github/workflows/unit_tests.yml
=> [CI] update runner ip env & fix show-statistics didn't run

gptqmodel/models/loader.py, gptqmodel/utils/model.py
=> fix time was not imported

.github/workflows/unit_tests.yml
=> [CI] install requirements.txt for m4

gptqmodel/models/auto.py
=> strip model path

gptqmodel/utils/model.py
=> fix import

gptqmodel/models/loader.py
=> auto enable flash_attn only when flash-attn was installed

gptqmodel/models/writer.py
=> fix unnecessary mkdir

tests/test_kernel_output_xpu.py
=> clean test_kernel_output_xpu.py

tests/test_olora_finetuning_xpu.py
=> add training callback

.github/workflows/release.yml
=> [CI] no need reinstall requirements

gptqmodel/nn_modules/qlinear/bitblas.py, gptqmodel/utils/importer.py, tests/test_q4_bitblas.py
=> fix bitblas choose IPEX in cuda env

tests/test_inference_result_xpu.py, tests/test_kernel_output_xpu.py
=> remove TritonV2QuantLinear for xpu test

gptqmodel/looper/module_looper.py, gptqmodel/models/definitions/ovis.py
Ovis official team here. Add [Ovis2](https://huggingface.co/collections/AIDC-AI/ovis2-67ab36c7e497429034874464) support and bug fix.
- support Qwen2.5-LM-based Ovis quantization
- support multiple types of calibration samples: pure text, multiple images, video
- fix KV-cache bug in looper/module_looper.py
=> [MODEL] add Ovis2 support and bug fix

.github/workflows/unit_tests.yml, tests/models/test_ovis2.py
=> add unit test for ovis2

gptqmodel/eora/eora.py, gptqmodel/looper/eora_processor.py, gptqmodel/looper/gptq_processor.py, gptqmodel/looper/named_module.py, gptqmodel/models/auto.py, gptqmodel/models/base.py, gptqmodel/models/definitions/__init__.py, gptqmodel/models/definitions/qwen3.py, gptqmodel/models/definitions/qwen3_moe.py, gptqmodel/models/writer.py, gptqmodel/nn_modules/qlinear/torch.py, gptqmodel/quantization/gptq.py
Support Qwen3 model.  Waiting for official weights to test.
=> add prelim qwen3 support

gptqmodel/models/auto.py, gptqmodel/models/base.py, gptqmodel/models/definitions/__init__.py, gptqmodel/models/definitions/dream.py, tests/models/model_test.py, tests/models/test_baichuan.py, tests/models/test_cohere.py, tests/models/test_cohere2.py, tests/models/test_deci.py, tests/models/test_dream.py, tests/models/test_exaone.py, tests/models/test_falcon.py, tests/models/test_hymba.py, tests/models/test_internlm2_5.py, tests/models/test_mistral.py, tests/models/test_mixtral.py, tests/models/test_mpt.py, tests/models/test_ovis2.py, tests/models/test_ovis_1_6_llama.py, tests/models/test_qwen2_5.py, tests/models/test_qwen2_5_vl.py, tests/models/test_qwen2_vl.py, tests/models/test_stablelm.py, tests/models/test_telechat2.py, tests/models/test_xverse.py, tests/models/test_yi.py
@jiacheng-ye We have never tested diffusion model quantization but can you check if this PR works? Thanks! I am not even sure what type of calibration dataset to use since difussion generate seems pretty funky, in a good way. =)
=> Dream Model Support

README.md, gptqmodel/models/auto.py, gptqmodel/models/definitions/decilm.py, gptqmodel/models/definitions/llama.py, gptqmodel/utils/model.py, tests/models/model_test.py, tests/models/test_nemotron_ultra.py
https://huggingface.co/nvidia/Llama-3_1-Nemotron-Ultra-253B-v1
Update: 
* `DeciLMDecoderLayer` in layer index 9-12 have no registered module parameters.
* `DeciLMDecoderLayer` in layer index 18-23 also have no registered module parameters. 
pytest is still running...
=> Nemotron Ultra Support

README.md, gptqmodel/looper/named_module.py, gptqmodel/models/_const.py, gptqmodel/nn_modules/hooked_linear.py, gptqmodel/quantization/config.py, gptqmodel/quantization/gptq.py, gptqmodel/utils/model.py
* faster `process_batch`
* support `_ConvNd` which should cover all convolutional modules
=> faster process_batch

.github/workflows/unit_tests.yml
=> [CI] remove torchao

gptqmodel/looper/dequantize_processor.py
=> Fix missing arg due to recent `Processor` api changes

.github/workflows/release.yml, setup.py
=> [CI] add release source with github's vm

gptqmodel/utils/model.py
Not sure how, but missed this in #1550.
=> Fix missing import

gptqmodel/models/auto.py
Reproduction：https://huggingface.co/glide-the/GLM-4-9B-Chat-0414-identity-4bits/
=> Supprt add glm4

README.md, gptqmodel/models/auto.py, gptqmodel/models/definitions/__init__.py, gptqmodel/models/definitions/mimo.py, gptqmodel/nn_modules/hooked_linear.py, tests/models/test_mimo.py
https://huggingface.co/XiaomiMiMo
=> Add Xiaomi MiMo model

.github/scripts/release_map.py, .github/workflows/release.yml
=> [CI] update release CI, add torch 2.7.0

gptqmodel/looper/module_looper.py, gptqmodel/models/auto.py, gptqmodel/models/definitions/base_qwen2_5_omni.py, gptqmodel/models/definitions/qwen2_5_omni.py, requirements.txt, tests/models/ovis/image_to_test_dataset.py, tests/models/test_qwen2_5_omni.py
This PR adds initial support for the **Qwen-Omni** model.
- ✅ Added compatibility for loading and running the Qwen-Omni model.
- ⚠️ Note: The current **quantized version** of Qwen-Omni only supports the `thinker` module. Other modules may not work correctly with quantization enabled.
Please review. Thanks!
=> feat: add Qwen-Omni support.

examples/benchmark/generation_speed.py
=> set_postfix is a tqdm function, no need anymore

gptqmodel/looper/module_looper.py
While testing with \GPTQModel\tests\test_lm_head.py, I encountered an error where the lm_head layer was not being quantized:
ERROR `lm_head` was not invoked, if it is a MoE module, it may lack sufficient calibration data routed to it.
which eventually caused the process to raise this error.Traceback (most recent call last):
ValueError: No quantization for lm_head module
The root cause is that when using **replace_module_with_hooked_tree**, the lm_head is not hooked
To address this, I added a separate piece of code to explicitly hook the lm_head, ensuring that it is properly included in the quantization process.
=> lm_head hooked

.github/workflows/unit_tests.yml
=> [CI] install jieba for test_pangu_alpha

.github/workflows/release.yml
=> [CI] update release matrix

.github/workflows/release.yml
=> [CI] don't compile 5090 for cuda < 12.8

.github/workflows/unit_tests.yml
=> [CI] Update unit test docker

.github/workflows/release.yml
=> [CI] fix release ci

tests/test_simple_quant.py
=> fix model path is not public

.github/workflows/unit_tests.yml
=> [CI] no need install uv

gptqmodel/models/auto.py, gptqmodel/models/definitions/glm4_moe.py
And probably other glm4_moe models.
I have quantized with this definition the GLM-4.5-Air model with padding to support tp8 and it works in vllm with tp8.
=> GLM-4.5-Air support

.github/workflows/release.yml
=> [CI] reduce wheel download size

.github/workflows/release.yml
=> [CI] add torch 2.8.0

pyproject.toml, setup.py
=> don't detect arch list when it has already been set & fix build-system requirments

.github/workflows/release.yml, .github/workflows/unit_tests.yml
=> [CI] use new docker

setup.py
=> temp disable awq gemm kernel due to failing ci

gptqmodel/looper/module_looper.py, gptqmodel/models/base.py, gptqmodel/nn_modules/hooked_linear.py, gptqmodel/nn_modules/qlinear/qqq.py, tests/test_qqq.py
fix https://github.com/ModelCloud/GPTQModel/issues/1875
~26% quantization time reduction for `test_qwen3_moe.py` Smaller gains 8% for small `test_llama3_2.py` test.
=> reduce forwarding to minimal

pyproject.toml
=> set licenses to apache

examples/eora/eora_generation.py, gptqmodel/looper/awq_processor.py, gptqmodel/looper/dequantize_processor.py, gptqmodel/looper/eora_processor.py, gptqmodel/looper/gptq_processor.py, gptqmodel/looper/loop_processor.py, gptqmodel/looper/native_processor.py, gptqmodel/looper/qqq_processor.py, gptqmodel/models/auto.py, gptqmodel/models/base.py, gptqmodel/utils/data.py, tests/models/model_test.py, tests/models/test_llama3_2.py, tests/test_awq.py, tests/test_awq_moe.py, tests/test_bits_new.py, tests/test_qqq.py, tests/test_quant_and_eora.py, tests/test_quant_and_eora_transformers.py, tests/test_quant_formats.py, tests/test_quant_time.py
new `calibration_sort` option: `asc`, `desc`, `shuffle`, `None`
`calibration_dataset_xxx` are now shortened to `calibration_xxx`
=> batch tweaks
